### ISSUE TITLE
Problems running TADA

### ISSUE THREAD

**Issue by Gedofs** [jakob-he/TADA#6]
Hi! I installed tadacnv via pip successfully however I can´t run it. 
<img width="1280" alt="Screenshot 2022-11-18 at 12 56 10" src="https://user-images.githubusercontent.com/94254364/202781896-2785143c-68c7-4f45-942f-8a2f44e55286.png">

I hope you can help me.

**Comment by jakob-he** [comment]
Hi @Gedofs!

This seems to be a dependency issue. I would recommend creating a new conda environment for tadacnv.
Then try reinstalling the package via pip. I only tested it using python 3.6. So the following could work:
```
conda create -n tada python=3.6
conda activate tada
pip install tadacnv
```
If the problem still persists let me know!

**Comment by Gedofs** [comment]
Thanks! Still issues. Seems like it is related to python 3.6

<img width="749" alt="Screenshot 2022-11-21 at 9 09 41" src="https://user-images.githubusercontent.com/94254364/203089492-0ef5326e-8624-4552-b3a0-049d82b88284.png">

**Comment by jakob-he** [comment]
Apparently, for the more recent osx-arm64 systems python versions < 3.8 are no longer  partof the conda forge build matrix.
You could try setting the conda environment up with python=3.8 instead. If there are still problems, I might have to update the tool for newer python versions.
